services: mongodb

sudo: false

language: ruby

cache: bundler

rvm:
  - 2.3.1
  - 2.3.0
  - 2.2
  - 2.1.1
  - 2.0.0
  - 1.9.3
  - rbx-2
  - jruby-19mode

matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: rbx-2
    - rvm: jruby-19mode
    - rvm: 2.0.0
      env: MONGOID_VERSION=6
    - rvm: 2.1.1
      env: MONGOID_VERSION=6
    - rvm: 2.2
      env: MONGOID_VERSION=6

env:
  - MONGOID_VERSION=3
  - MONGOID_VERSION=4
  - MONGOID_VERSION=5
  - MONGOID_VERSION=6
